server:
  port: 8130 #服务端口

spring:
  profiles:
    active: dev #环境设置
  application:
    name: service-vod #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: #默认为空

  servlet:
    multipart:
      max-file-size: 2048MB #最大上传单个文件大小：默认1M
      max-request-size: 2048MB #最大置总上传的数据大小 ：默认10M

#阿里云vod视频存储
aliyun:
  vod:
    accesskeyId:
    accesskeySecret:
    #转码模板组id
    templateGroupId:
    #工作流id
    workflowId:


