version: '3'

services:
  mongo:
    image: mongo:latest
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - /d/Docker/docker/mongoDPlayer/db0:/data/db
  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - "127.0.0.1:6380:6379"
    volumes:
      - /d/Docker/docker/redisDplayer/data:/data
      - /d/Docker/docker/redisDplayer/redis.conf:/usr/local/redis/redis.conf
      - /d/Docker/docker/redisDplayer/logs:/logs
    environment: 
      - TZ=Asia/Shanghai 
    command: ["redis-server","/usr/local/redis/redis.conf"]
  web:
    build: .
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    ports:
      - 1207:1207
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
      MONGO_HOST: "mongo"
      MONGO_PORT: 27017
      MONGO_DATABASE: "danmaku"
    volumes:
      - /d/Docker/docker/webDPlayer/logs:/usr/src/app/logs
      - /d/Docker/docker/webDPlayer/pm2logs:/root/.pm2/logs
